export enum ServiceType {
  HAIRCUT = 'HAIRCUT',
  HAIR_COLORING = 'HAIR_COLORING',
  HAIR_STYLING = 'HAIR_STYLING',
  HAIR_TREATMENT = 'HAIR_TREATMENT',
  HAIR_REMOVAL = 'HAIR_REMOVAL',
  NAIL_CARE = 'NAIL_CARE',
  SKIN_CARE = 'SKIN_CARE',
  MAKE_UP = 'MAKE_UP',
  OTHERS = 'OTHERS'
}